# This is a basic workflow to help you get started with Actions
name: Scheduled Web rebuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "5 8 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  runDataUpdate:
    # The type of runner that the job will run on
    name: Run NIST Viz Portal update
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run NIST Viz Portal update
      uses: ./_action-update
      env:
        BRANCH_NAME: master
        BOT_USER: usnistgov
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
